### ISSUE TITLE
Unable to Add Accessory

### ISSUE THREAD

**Issue by jurekjure** [Hernas/homebridge-panasonic-heat-pump#2] opened 2022-09-26 19:09 UTC
When I try to add the accesory to HomeKit - By scanning the "Bridge" QR code from HOOBS (Separate bridge for every plugin) I get a notification in HomeApp:

Unable to Add Accessory
Accessory is out of compliance

If I close the popup window and try to add it again, HomeAPP pops up a warning that the accessory is already added and that I need to reset the accessory to add it again.

If I then "reset the accessory" - that is uninstall the plugin in HOOBS and reinstall it - and retry to add it ... tho whole thing happens again.

**Comment by bimusiek** [comment] 2022-09-27 11:00
Hey, I am not able to check why HOOBS does not show the accessory. I am using Homebridge and it works as expected. Feel free to open Pull Request with the fix! 👍

**Comment by jurekjure** [comment] 2022-09-27 15:46
Well I'm not on the "programming" side of things. Just an enthusiast HomeKit and Hoobs user. But it would be great if we could come up with a solution?

**Comment by jurekjure** [comment] 2022-09-27 20:12
https://user-images.githubusercontent.com/54580999/192625927-5520bbf5-74dd-478d-9e76-05a872e61c6e.MOV

**Comment by jurekjure** [comment] 2022-09-27 20:18
Maybe this helpes ...
Log:

[27/09/2022, 22:08] [Hub] Aquarea HOOBS starting
[27/09/2022, 22:08] [Aquarea HOOBS] Loaded plugin 'homebridge-panasonic-heat-pump'
[27/09/2022, 22:08] [Aquarea HOOBS] Registering platform 'homebridge-panasonic-heat-pump.PanasonicHeatPumpHomebridgePlugin'
[27/09/2022, 22:08] [Aquarea HOOBS] Loading 1 platforms...
[27/09/2022, 22:08] [Aquarea HOOBS] Bridge is running on port 51866.
[27/09/2022, 22:08] [Aquarea HOOBS] Adding new accessory: Aquarea
[27/09/2022, 22:10] [Aquarea HOOBS] [ERROR] [Aquarea HOOBS F31C@Aquarea@Floors@Current Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
[27/09/2022, 22:10] [Aquarea HOOBS] [ERROR] [Aquarea HOOBS F31C@Aquarea@Floors@Current Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 17
[27/09/2022, 22:10] [Aquarea HOOBS] [ERROR] [Aquarea HOOBS F31C@Aquarea@Water@Current Temperature] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics

**Comment by bimusiek** [comment] 2022-09-27 20:37
I am working on new version, not sure if it will fix your issue though. 

To be able to investigate I would either need your credentials to Comfort Cloud or response of the device details from Comfort Cloud.

You can do the second one by opening Networking tab in Comfort Cloud, waiting a little bit and saving the response of ttps://aquarea-smart.panasonic.com/remote/v1/api/devices/[uuid]

**Comment by jurekjure** [comment] 2022-09-27 20:50
Sadly I cannot find the Networking tab within the Comfort Cloud App

This is all I can get to

![image](https://user-images.githubusercontent.com/54580999/192632706-a8d6b4f3-62c5-47f6-a975-be42df5a576c.png)

**Comment by bimusiek** [comment] 2022-09-27 20:51
I meant on your computer:
https://aquarea-smart.panasonic.com/remote/a2wControl

**Comment by bimusiek** [comment] 2022-09-27 21:49
Please also try the newest version, I have updated a lot and added new functionality as well.

**Comment by jurekjure** [comment] 2022-09-28 06:20
I've updated it, but I'll try how (and if) it works when I'm at home ... this evening

Relating the info from Comfort Cloud:
Can you please help me find what you need?

https://user-images.githubusercontent.com/54580999/192702628-de4bd37c-e452-4367-a27f-a48eb7a14e04.mov

**Comment by bimusiek** [comment] 2022-09-28 06:41
The last one with long string of random characters. This is your device guid and the response should have device details like temp etc. Just right click on it and export it as HAR.

**Comment by jurekjure** [comment] 2022-09-28 07:40
Ok, here it is, adding it as an attachment to no clutter (even more) this thread
[aquarea-smart.panasonic.com.har.zip](https://github.com/bimusiek/homebridge-panasonic-heat-pump/files/9662585/aquarea-smart.panasonic.com.har.zip)

**Comment by bimusiek** [comment] 2022-09-28 08:49
@jurekjure Ok, I think I see the issue. Looks like your water tank does not have temp sensor or the heat pump is not reporting it. I have to make some adjustments to it, probably it will show temperature that is set to be, not the actual one as there is no sensor.

**Comment by jurekjure** [comment] 2022-09-28 09:27
Great that you found it.
If your talking about water tank as drinking/shovering/... supply I do not use this option. I only use the heat pump for heating.

**Comment by bimusiek** [comment] 2022-09-28 09:29
Hmm, ok. Can you screenshot Comfort Cloud? I have 2 things there, one is floor heating and below it I see the water heater.

**Comment by jurekjure** [comment] 2022-09-28 09:43
Sure
![Screenshot 2022-09-28 at 11 42 28](https://user-images.githubusercontent.com/54580999/192746714-34fe588b-7b71-42c8-8360-455a34fc50c1.png)

**Comment by jurekjure** [comment] 2022-09-28 09:44
![Screenshot 2022-09-28 at 11 44 12](https://user-images.githubusercontent.com/54580999/192747029-41d3f2b9-c986-4ee6-8e8e-248d8588088e.png)

**Comment by bimusiek** [comment] 2022-09-28 10:37
Ok, thank you. I found a way to check if heat pump has tank and if it has cooling enabled.
```json
{
  "deviceGuid": "xxx",
  "configration": [
    {
      "zoneInfo": [
        {
          "zoneSensor": "Water temperature",
          "coolMode": "enable",
          "heatSensor": "Compensation curve",
          "coolSensor": "Compensation curve",
          "outdoorType": "STD",
          "zoneId": 1,
          "zoneType": "Room",
          "zoneName": "Home"
        }
      ],
      "a2wName": "HeatPump",
      "operationMode": "Heat",
      "deviceGuid": "xxx",
      "lastErrorNumber": "",
      "bivalent": "No",
      "specialStatus": 0,
      "tankInfo": [
        {
          "tankType": "Internal",
          "tank": "Yes"
        }
      ],
      "firmVersion": "040102"
    }
  ]
}
```

I will make it work in a way like a tank does. So if you set the mode to cooling, it will switch it to OFF. And if you set it to auto, it will switch it to HEAT.

**Comment by bimusiek** [comment] 2022-09-28 11:04
Ok, the new version is published. Under new NPM package though:
https://www.npmjs.com/package/@hernas/homebridge-panasonic-heat-pump

As I have moved it to organisation.

Please let me now if it works so I can close the issue :)

**Comment by jurekjure** [comment] 2022-09-28 18:38
Hey, I tried finding the plugin through Hoobs, but only the old version can be found. I guess I'll have to wait a bit until the list is updated. I tried even through the Hoobs terminal using "npm i @hernas/homebridge-panasonic-heat-pump" ... terminal states it's installed ... but it cannot be found or used. So ... I guess I'm waiting. 
But I'll definitely let you know.
Thanks for all the effort!

**Comment by bimusiek** [comment] 2022-09-29 10:25
The package will be named the same `homebridge-panasonic-heat-pump`, it will be just installed from scoped npm repo: `@hernas/homebridge-panasonic-heat-pump`. 

Just check if it sees the 1.3.0 version and try it out. If it does not work, please post the logs here so I can investigate.

**Comment by jurekjure** [comment] 2022-09-29 16:45
Still no change 🤷‍♂️![image](https://user-images.githubusercontent.com/54580999/193090387-b182a53e-2328-467a-9320-a2f422881f8c.jpeg)![image](https://user-images.githubusercontent.com/54580999/193090409-b6e22e30-7152-4802-94fa-bfdde42076e7.jpeg)

**Comment by jurekjure** [comment] 2022-09-30 06:06
https://plugins.hoobs.org/plugin/homebridge-panasonic-heat-pump

**Comment by jurekjure** [comment] 2022-10-04 17:49
Hey!

Finally I got it installed (talked to Hoobs support, so they published the new plugin) and connected to homekit.
It displays, but does not work.
1. I cannot turn it on - if i change it's state from OFF to HEAT, COOL or AUTO it stays in that setting for just a couple of seconds and switches back to OFF.
2. If I change the temperature in HomeKit it affects the "set" (in aquarea app) parameter, which is the one which can be set from -5 to +5 (the variation from the default temperature setting). Bot not at any time or input does it turn the heat pump on.

Here's the log
04/10/2022, 19:40:23Aquarea HOOBSERROR[Aquarea HOOBS 86C0@On] The write handler for the characteristic 'On' on the accessory 'Heat Pump' was slow to respond! 
04/10/2022, 19:40:31Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:40:31Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:40:31Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number)
04/10/2022, 19:40:36Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:40:36Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:40:36Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:40:41Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:40:41Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:40:41Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:40:49Aquarea HOOBSERROR[Aquarea HOOBS 86C0@On] The write handler for the characteristic 'On' on the accessory 'Heat Pump' was slow to respond! 
04/10/2022, 19:40:55Aquarea HOOBSERROR[Aquarea HOOBS 86C0@On] The write handler for the characteristic 'On' on the accessory 'Heat Pump' was slow to respond! 
04/10/2022, 19:41:02Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:41:02Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:41:02Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:41:08Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:41:08Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:41:08Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:41:13Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:41:13Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:41:13Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:41:17Aquarea HOOBSERROR[Aquarea HOOBS 86C0@On] The write handler for the characteristic 'On' on the accessory 'Heat Pump' was slow to respond! 
04/10/2022, 19:44:50Aquarea HOOBSERROR[Aquarea HOOBS 86C0@On] The write handler for the characteristic 'On' on the accessory 'Heat Pump' was slow to respond! 
04/10/2022, 19:44:58Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'minValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:44:58Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] Characteristic Property 'maxValue' must be a finite number, received "NaN" (number) 
04/10/2022, 19:44:58Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:44:59Aquarea HOOBSERROR[Aquarea HOOBS 86C0@Heat Pump@Floor Heating@Target Temperature] characteristic value expected valid finite number and received "NaN" (number) 
04/10/2022, 19:45:03Aquarea HOOBSERROR[Aquarea HOOBS 86C0@On] The write handler for the characteristic 'On' on the accessory 'Heat Pump' was slow to respond!

**Comment by bimusiek** [comment] 2022-10-05 07:54
I can fix it, but the problem is that I don't have cooling and water turned off. 
So I would need you to open Chrome on your PC, open Networking tab, turn the heating off and on and send me the HAR requests again. HAR request of the turning it on and off. It will also have this long random string in Networking tab. 

My email: m@hern.as (send here, for privacy reasons)

**Comment by jurekjure** [comment] 2022-10-05 16:54
Ok, I've done it, it throws out four "long strings" as we discussed before, i'll send the files to your email.
<img width="536" alt="Screenshot 2022-10-05 at 18 52 45" src="https://user-images.githubusercontent.com/54580999/194117617-296a624d-d6ed-4865-bb61-6f74de0e1ca6.png">

**Comment by jurekjure** [comment] 2022-10-12 17:22
After the public release you posted, the update was reachable through hoobs, so I updated to 1.3.3, but no change :( 

https://user-images.githubusercontent.com/54580999/195407403-44bcab0a-b25a-48fc-ab43-12f61b87893d.mov

`
2/10/2022, 19:10:52Aquarea HOOBSERROR[Aquarea HOOBS 6863@Target Temperature] The read handler for the characteristic 'Target Temperature' on the accessory 'Heat Pump' didn't respond at all!. Please check that you properly call the callback!
12/10/2022, 19:10:52Aquarea HOOBSERROR[Aquarea HOOBS 6863@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'Heat Pump' didn't respond at all!. Please check that you properly call the callback!
12/10/2022, 19:10:52Aquarea HOOBSERROR[Aquarea HOOBS 6863@Target Heating Cooling State] The read handler for the characteristic 'Target Heating Cooling State' on the accessory 'Heat Pump' didn't respond at all!. Please check that you properly call the callback!
12/10/2022, 19:10:55Aquarea HOOBSERROR[Aquarea HOOBS 6863@Target Heating Cooling State] The read handler for the characteristic 'Target Heating Cooling State' on the accessory 'Heat Pump' was slow to respond!
12/10/2022, 19:10:55Aquarea HOOBSERROR[Aquarea HOOBS 6863@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'Heat Pump' was slow to respond!
12/10/2022, 19:10:55Aquarea HOOBSERROR[Aquarea HOOBS 6863@Target Temperature] The read handler for the characteristic 'Target Temperature' on the accessory 'Heat Pump' was slow to respond!
`

**Comment by bimusiek** [comment] 2022-10-12 17:24
Hey, I did not yet work on your issue. I will see if I have time over weekend. 
Version 1.3.3 basically added flags for hiding comfort and eco mode and outside temperature sensor. Plus some stability improvements.

**Comment by jurekjure** [comment] 2022-10-12 17:26
Oh, ok, sorry then. Thank you!

**Comment by bimusiek** [comment] 2022-12-06 15:04
@jurekjure Please check https://github.com/Hernas/homebridge-panasonic-heat-pump/releases/tag/v1.3.7 as it should have a fix for you.

Basically if you have cooling mode disabled, there is no option to change operationMode and based on the logs you have sent me we need to send `-1` as operation mode. And I was trying to send `1` to enable heating thus there was a problem.

Please tell me if this fix helps, otherwise I have to look further.

**Comment by jurekjure** [comment] 2022-12-06 17:48
Hey, thanks for the effort but sadly, there seems to be no improvement. Homekit reflects settings made in the Aquarea Smart Cloud (but it takes minutes to reflect). It doesnt work the other way round: from HK to Aquarea.
Also the HK tile seems to directly reflect the Aquarea screen, but it displays the "set"  temp as "heating to".

![image](https://user-images.githubusercontent.com/54580999/205984481-c90cb75e-582b-486f-b705-ef459a745bab.jpeg)
![image](https://user-images.githubusercontent.com/54580999/205984503-08ddaa7b-e2d0-432d-a018-6c75887fac9d.jpeg)
![bimage](https://user-images.githubusercontent.com/54580999/205984583-cd2c126a-ab2a-4570-a92f-b382b7780414.jpeg)

**Comment by bimusiek** [comment] 2022-12-06 17:51
Did you try to mark it as HEAT or OFF? I fixed this specific issue, the temperature setting is somehow tricky.

**Comment by jurekjure** [comment] 2022-12-06 18:00
I did. If you set it from heat to  off it resets to heat after some time and it does not reflect to Aquarea.

**Comment by bimusiek** [comment] 2022-12-06 18:03
Wait a moment, I see it now. Basically in my case when I have water tank installed, if I switch both off, the one will be turned on. So if I switch off the heater, it will redirect the heat to the tank. If I switch off the tank, it will redirect heat to the heater. 

This is what I want as it is tricky in HomeKit to rely on 2 devices at the same time so I rather operate which one works. 
But in your case, I have to turn off whole heat pump off and on. 

Could you confirm it with me? If you turn the heating off in the Cloud, the heatpump will also show as off?

**Comment by jurekjure** [comment] 2022-12-06 18:16
If you are asking: if I turn off the switch next to "set to -5" (in Aquarea Cloud) does the heat pump turn off?
Yes it does, that's correct.
Didn't know it functions like that when you have a water tank. Smart.

**Comment by bimusiek** [comment] 2022-12-06 18:33
Ok, give me 30min. I am rewriting code to handle both heaters off. I just tested on mine and indeed, when I turn off water heating but keep floor heating it works. Same if other way around. 

But when I turn off both in HK, heatpump should turn off and it does not currently. It switches to one of those.

**Comment by bimusiek** [comment] 2022-12-06 19:15
@jurekjure Please try https://github.com/Hernas/homebridge-panasonic-heat-pump/releases/tag/v1.4.0 

I have improved it a lot, even in my case it shows correct statuses right now. Also, this should fix the issue the error you have got before.

**Comment by jurekjure** [comment] 2022-12-06 20:07
Great, and I would try it, but there is again a problem with the HOOBS plugin registry - I cannot update, it states the last version is 1.3.7. Even thou it is clear from the body of the page, that is not correct. 
Plugin @ HOOBS https://plugins.hoobs.org/plugin/@hernas/homebridge-panasonic-heat-pump
I sent them an email. Will let you know when I can update and try it

**Comment by jurekjure** [comment] 2022-12-06 20:45
Uh, oh, works - the update and also the plugin! 
I can control it from HK, still a bit slow and the temp display is wierd (as stated before), but it works! Great! Thank you

**Comment by jurekjure** [comment] 2022-12-06 20:46
And its a bit unstable - accesory not responding - have to restart the hoobs bridge, than its ok.

**Comment by bimusiek** [comment] 2022-12-06 21:11
I would recommend simply setting Homebridge. Based on r/homebridge subreddit I can see a lot of people migrating and having no issues. 

I will have to change architecture of the plugin to make it more responsive but thats for later.

**Closed as completed by bimusiek** 2022-12-06 21:11 UTC
Labels: bug
